// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// To configure Firebase properly:
/// 1. Go to https://console.firebase.google.com/
/// 2. Create a new project or select existing one
/// 3. Add your app (Android/iOS/Web)
/// 4. Download the configuration files
/// 5. Replace the values below with your actual Firebase configuration
/// 6. Enable Firestore Database in Firebase Console
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase configuration
  // Get these values from Firebase Console > Project Settings > General > Your apps
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // Replace with your Web API Key
    appId:
        '1:YOUR_PROJECT_NUMBER:web:YOUR_WEB_APP_ID', // Replace with your Web App ID
    messagingSenderId:
        'YOUR_MESSAGING_SENDER_ID', // Replace with your Messaging Sender ID
    projectId: 'your-project-id', // Replace with your Project ID
    authDomain:
        'your-project-id.firebaseapp.com', // Replace with your Auth Domain
    storageBucket:
        'your-project-id.appspot.com', // Replace with your Storage Bucket
    measurementId:
        'G-YOUR_MEASUREMENT_ID', // Optional: Replace with your Measurement ID
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Replace with your Android API Key
    appId:
        '1:YOUR_PROJECT_NUMBER:android:YOUR_ANDROID_APP_ID', // Replace with your Android App ID
    messagingSenderId:
        'YOUR_MESSAGING_SENDER_ID', // Replace with your Messaging Sender ID
    projectId: 'your-project-id', // Replace with your Project ID
    storageBucket:
        'your-project-id.appspot.com', // Replace with your Storage Bucket
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with your iOS API Key
    appId:
        '1:YOUR_PROJECT_NUMBER:ios:YOUR_IOS_APP_ID', // Replace with your iOS App ID
    messagingSenderId:
        'YOUR_MESSAGING_SENDER_ID', // Replace with your Messaging Sender ID
    projectId: 'your-project-id', // Replace with your Project ID
    storageBucket:
        'your-project-id.appspot.com', // Replace with your Storage Bucket
    iosBundleId:
        'com.yourcompany.ipoedgeApp', // Replace with your iOS Bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with your macOS API Key
    appId:
        '1:YOUR_PROJECT_NUMBER:macos:YOUR_MACOS_APP_ID', // Replace with your macOS App ID
    messagingSenderId:
        'YOUR_MESSAGING_SENDER_ID', // Replace with your Messaging Sender ID
    projectId: 'your-project-id', // Replace with your Project ID
    storageBucket:
        'your-project-id.appspot.com', // Replace with your Storage Bucket
    iosBundleId:
        'com.yourcompany.ipoedgeApp', // Replace with your macOS Bundle ID
  );
}
